services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge